application: predictplus
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /assets
  static_dir: assets
  
- url: /predict.php
  script: predict.php
  login: required

- url: .*
  script: main.php
